from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

inline_ukraine = InlineKeyboardButton('Ukraine', callback_data='ukraine')
inline_netherlands = InlineKeyboardButton('The Netherlands', callback_data='netherlands')
inline_norway = InlineKeyboardButton('Norway', callback_data='norway')
inline_greece = InlineKeyboardButton('Greece', callback_data='greece')
inline_albania = InlineKeyboardButton('Albania', callback_data='albania')
inline_armenia = InlineKeyboardButton('Armenia', callback_data='armenia')
inline_moldova = InlineKeyboardButton('Moldova', callback_data='moldova')
inline_portugal = InlineKeyboardButton('Portugal', callback_data='portugal')
inline_swiss = InlineKeyboardButton('Switzerland', callback_data='swiss')
inline_austria = InlineKeyboardButton('Austria', callback_data='austria')
inline_lithuania = InlineKeyboardButton('Lithuania', callback_data='lithuania')
inline_latvia = InlineKeyboardButton('Latvia', callback_data='latvia')
inline_croatia = InlineKeyboardButton('Croatia', callback_data='croatia')
inline_iceland = InlineKeyboardButton('Iceland', callback_data='iceland')
inline_slovenia = InlineKeyboardButton('Slovenia', callback_data='slovenia')
inline_denmark = InlineKeyboardButton('Denmark', callback_data='denmark')
inline_bulgaria = InlineKeyboardButton('Bulgaria', callback_data='bulgaria')
inline_kb = InlineKeyboardMarkup(row_width=4)
inline_kb.row(inline_greece, inline_norway, inline_netherlands, inline_ukraine)
inline_kb.row(inline_moldova, inline_portugal, inline_armenia, inline_albania)
inline_kb.row(inline_latvia, inline_lithuania, inline_swiss, inline_austria)
inline_kb.row(inline_bulgaria, inline_denmark, inline_iceland, inline_croatia, inline_slovenia)

inline_sweden = InlineKeyboardButton('Sweden', callback_data='sweden')
inline_poland = InlineKeyboardButton('Poland', callback_data='poland')
inline_estonia = InlineKeyboardButton('Estonia', callback_data='estonia')
inline_finland = InlineKeyboardButton('Finland', callback_data='finland')
inline_azerbaijan = InlineKeyboardButton('Azerbaijan', callback_data='azerbaijan')
inline_australia = InlineKeyboardButton('Australia', callback_data='australia')
inline_serbia = InlineKeyboardButton('Serbia', callback_data='serbia')
inline_belgium = InlineKeyboardButton('Belgium', callback_data='belgium')
inline_czech = InlineKeyboardButton('Czech Republic', callback_data='czech')
inline_cyprus = InlineKeyboardButton('Cyprus', callback_data='cyprus')
inline_malta = InlineKeyboardButton('Malta', callback_data='malta')
inline_romania = InlineKeyboardButton('Romania', callback_data='romania')
inline_san = InlineKeyboardButton('San Marino', callback_data='marino')
inline_montenegro = InlineKeyboardButton('Montenegro', callback_data='montenegro')
inline_israel = InlineKeyboardButton('Israel', callback_data='israel')
inline_macedonia = InlineKeyboardButton('North Macedonia', callback_data='macedonia')
inline_ireland = InlineKeyboardButton('Ireland', callback_data='ireland')
inline_georgia = InlineKeyboardButton('Georgia', callback_data='georgia')
inline_kb_2 = InlineKeyboardMarkup(row_width=4)
inline_kb_2.row(inline_ireland, inline_israel, inline_san, inline_macedonia)
inline_kb_2.row(inline_malta, inline_montenegro, inline_czech, inline_cyprus)
inline_kb_2.row(inline_serbia, inline_sweden, inline_poland, inline_romania, inline_belgium)
inline_kb_2.row(inline_finland, inline_australia, inline_azerbaijan, inline_estonia, inline_georgia)

inline_italy = InlineKeyboardButton('Italy', callback_data='italy')
inline_uk = InlineKeyboardButton('The UK', callback_data='uk')
inline_spain = InlineKeyboardButton('Spain', callback_data='spain')
inline_france = InlineKeyboardButton('France', callback_data='france')
inline_germany = InlineKeyboardButton('Germany', callback_data='germany')
inline_kb_3 = InlineKeyboardMarkup(row_width=5)
inline_kb_3.row(inline_france, inline_uk, inline_spain, inline_germany, inline_italy)

inline_vote_norway = InlineKeyboardButton('Norway', callback_data='Norway')
inline_voting = InlineKeyboardMarkup(row_width=7)
inline_voting.add(inline_vote_norway)
